import type { Lead } from "./types";

/* Dados de demonstração — substituídos pelas duas listas reais (Clientes e
 * Prospects) na primeira importação. Servem só para o board não nascer vazio. */

const hojeMenos = (dias: number) =>
  new Date(Date.now() - dias * 86400000).toISOString();

export const MOCK_LEADS: Lead[] = [
  // ===== CLIENTES (base já atendida pela consultoria) =====
  {
    id: "c1",
    nome: "Ricardo Almeida",
    empresa: "Almeida Participações",
    cargo: "CEO",
    telefone: "11987654001",
    email: "ricardo@almeidapart.com.br",
    lista: "clientes",
    etapa: "comprou",
    tags: ["âncora", "quente"],
    notas: "Primeiro sim. Confirmou os 2 dias. Levar o sócio.",
    atualizadoEm: hojeMenos(1),
    criadoEm: hojeMenos(20),
  },
  {
    id: "c2",
    nome: "Fernanda Costa",
    empresa: "Grupo FC Saúde",
    cargo: "Diretora Executiva",
    telefone: "11987654002",
    email: "fernanda@fcsaude.com.br",
    lista: "clientes",
    etapa: "em_negociacao",
    tags: ["quente"],
    notas: "Quer parcelar. Aguardando link de pagamento.",
    atualizadoEm: hojeMenos(2),
    criadoEm: hojeMenos(18),
  },
  {
    id: "c3",
    nome: "Paulo Menezes",
    empresa: "Menezes Logística",
    cargo: "Sócio-fundador",
    telefone: "11987654003",
    lista: "clientes",
    etapa: "respondeu_positivo",
    tags: [],
    notas: "Interessado, pediu para retomar semana que vem.",
    atualizadoEm: hojeMenos(4),
    criadoEm: hojeMenos(15),
  },
  {
    id: "c4",
    nome: "Beatriz Tavares",
    empresa: "BT Consultoria",
    cargo: "CEO",
    telefone: "11987654004",
    lista: "clientes",
    etapa: "recebeu_convite",
    tags: [],
    atualizadoEm: hojeMenos(3),
    criadoEm: hojeMenos(10),
  },
  {
    id: "c5",
    nome: "Henrique Só",
    empresa: "Sony Educação",
    cargo: "Diretor",
    telefone: "11987654005",
    lista: "clientes",
    etapa: "nao_respondeu",
    tags: ["follow-up"],
    notas: "Convite lido, sem resposta. Tentar por áudio.",
    atualizadoEm: hojeMenos(8),
    criadoEm: hojeMenos(12),
  },
  {
    id: "c6",
    nome: "Marina Lopes",
    empresa: "Lopes & Cia",
    cargo: "CFO",
    telefone: "11987654006",
    lista: "clientes",
    etapa: "aguardando_convite",
    tags: [],
    criadoEm: hojeMenos(2),
  },
  {
    id: "c7",
    nome: "Carlos Bavaresco",
    empresa: "CB Investimentos",
    cargo: "Sócio",
    telefone: "11987654007",
    lista: "clientes",
    etapa: "respondeu_negativo",
    tags: [],
    notas: "Viaja na data. Manter para o EAD em 2027.",
    atualizadoEm: hojeMenos(5),
    criadoEm: hojeMenos(14),
  },

  // ===== PROSPECTS (rede fria / indicações) =====
  {
    id: "p1",
    nome: "André Nogueira",
    empresa: "Nogueira Tech",
    cargo: "CEO",
    telefone: "11912340001",
    lista: "prospects",
    etapa: "aguardando_convite",
    tags: ["indicação"],
    notas: "Indicado pelo Ricardo Almeida.",
    criadoEm: hojeMenos(1),
  },
  {
    id: "p2",
    nome: "Juliana Reis",
    empresa: "Reis Franquias",
    cargo: "Fundadora",
    telefone: "11912340002",
    lista: "prospects",
    etapa: "recebeu_convite",
    tags: [],
    atualizadoEm: hojeMenos(2),
    criadoEm: hojeMenos(6),
  },
  {
    id: "p3",
    nome: "Gustavo Pires",
    empresa: "GP Holding",
    cargo: "Presidente",
    telefone: "11912340003",
    lista: "prospects",
    etapa: "respondeu_positivo",
    tags: ["quente"],
    notas: "Pediu a agenda dos 2 dias.",
    atualizadoEm: hojeMenos(1),
    criadoEm: hojeMenos(7),
  },
  {
    id: "p4",
    nome: "Tatiane Moura",
    empresa: "Moura Cosméticos",
    cargo: "CEO",
    telefone: "11912340004",
    lista: "prospects",
    etapa: "nao_respondeu",
    tags: ["follow-up"],
    atualizadoEm: hojeMenos(9),
    criadoEm: hojeMenos(11),
  },
  {
    id: "p5",
    nome: "Roberto Lima",
    empresa: "Lima Agro",
    cargo: "Sócio-diretor",
    telefone: "11912340005",
    lista: "prospects",
    etapa: "em_negociacao",
    tags: [],
    notas: "Avaliando levar equipe (3 vagas).",
    atualizadoEm: hojeMenos(3),
    criadoEm: hojeMenos(9),
  },
];
